const projects = [
  {
    id: "1",
    name: "Website Redesign",
    description: "Redesign our company website to improve user experience.",
    img: "",
    startDate: 1679404800,
    deadline: 1688985600,
    teamMembers: [
      {
        id: "1",
        name: "John Doe",
        img: "",
        email: "john@example.com",
      },
      {
        id: "2",
        name: "Alice Smith",
        img: "",
        email: "alice@example.com",
      },
      {
        id: "3",
        name: "Bob Johnson",
        img: "",
        email: "bob@example.com",
      },
      {
        id: "4",
        name: "Emily Brown",
        img: "",
        email: "emily@example.com",
      },
      {
        id: "5",
        name: "Michael Wilson",
        img: "",
        email: "michael@example.com",
      },
      {
        id: "6",
        name: "Sophia Lee",
        img: "",
        email: "sophia@example.com",
      },
      {
        id: "7",
        name: "David Martinez",
        img: "",
        email: "david@example.com",
      },
      {
        id: "8",
        name: "Emma Taylor",
        img: "",
        email: "emma@example.com",
      },
      {
        id: "9",
        name: "James Rodriguez",
        img: "",
        email: "james@example.com",
      },
      {
        id: "10",
        name: "Olivia Nguyen",
        img: "",
        email: "olivia@example.com",
      },
    ],
    recentActivities: ["Wireframes designed", "Homepage development started"],
    createdAt: 1679404800,
    updatedAt: 1689216000,
  },
  {
    id: "2",
    name: "Mobile App Development",
    description: "Develop a mobile application for Android and iOS platforms.",
    img: "",
    startDate: 1679404800,
    deadline: 1689747200,
    teamMembers: [
      {
        id: "1",
        name: "John Doe",
        img: "",
        email: "john@example.com",
      },
      {
        id: "2",
        name: "Alice Smith",
        img: "",
        email: "alice@example.com",
      },
      {
        id: "3",
        name: "Bob Johnson",
        img: "",
        email: "bob@example.com",
      },
      {
        id: "4",
        name: "Emily Brown",
        img: "",
        email: "emily@example.com",
      },
      {
        id: "5",
        name: "Michael Wilson",
        img: "",
        email: "michael@example.com",
      },
      {
        id: "6",
        name: "Sophia Lee",
        img: "",
        email: "sophia@example.com",
      },
      {
        id: "7",
        name: "David Martinez",
        img: "",
        email: "david@example.com",
      },
      {
        id: "8",
        name: "Emma Taylor",
        img: "",
        email: "emma@example.com",
      },
      {
        id: "9",
        name: "James Rodriguez",
        img: "",
        email: "james@example.com",
      },
      {
        id: "10",
        name: "Olivia Nguyen",
        img: "",
        email: "olivia@example.com",
      },
    ],
    recentActivities: ["UI/UX designs finalized"],
    createdAt: 1679404800,
    updatedAt: 1689484800,
  },
  {
    id: "3",
    name: "Marketing Campaign",
    description:
      "Plan and execute a marketing campaign for the new product launch.",
    img: "",
    startDate: 1679404800,
    deadline: 1689753600,
    teamMembers: [
      {
        id: "1",
        name: "John Doe",
        img: "",
        email: "john@example.com",
      },
      {
        id: "2",
        name: "Alice Smith",
        img: "",
        email: "alice@example.com",
      },
      {
        id: "3",
        name: "Bob Johnson",
        img: "",
        email: "bob@example.com",
      },
      {
        id: "4",
        name: "Emily Brown",
        img: "",
        email: "emily@example.com",
      },
      {
        id: "5",
        name: "Michael Wilson",
        img: "",
        email: "michael@example.com",
      },
      {
        id: "6",
        name: "Sophia Lee",
        img: "",
        email: "sophia@example.com",
      },
      {
        id: "7",
        name: "David Martinez",
        img: "",
        email: "david@example.com",
      },
      {
        id: "8",
        name: "Emma Taylor",
        img: "",
        email: "emma@example.com",
      },
      {
        id: "9",
        name: "James Rodriguez",
        img: "",
        email: "james@example.com",
      },
      {
        id: "10",
        name: "Olivia Nguyen",
        img: "",
        email: "olivia@example.com",
      },
    ],
    recentActivities: [],
    createdAt: 1679404800,
    updatedAt: 1679404800,
  },
  {
    id: "4",
    name: "Software Upgrade",
    description: "Upgrade the company's ERP software to the latest version.",
    img: "",
    startDate: 1679404800,
    deadline: 1687584000,
    teamMembers: [
      {
        id: "1",
        name: "John Doe",
        img: "",
        email: "john@example.com",
      },
      {
        id: "2",
        name: "Alice Smith",
        img: "",
        email: "alice@example.com",
      },
      {
        id: "3",
        name: "Bob Johnson",
        img: "",
        email: "bob@example.com",
      },
      {
        id: "4",
        name: "Emily Brown",
        img: "",
        email: "emily@example.com",
      },
      {
        id: "5",
        name: "Michael Wilson",
        img: "",
        email: "michael@example.com",
      },
      {
        id: "6",
        name: "Sophia Lee",
        img: "",
        email: "sophia@example.com",
      },
      {
        id: "7",
        name: "David Martinez",
        img: "",
        email: "david@example.com",
      },
      {
        id: "8",
        name: "Emma Taylor",
        img: "",
        email: "emma@example.com",
      },
      {
        id: "9",
        name: "James Rodriguez",
        img: "",
        email: "james@example.com",
      },
      {
        id: "10",
        name: "Olivia Nguyen",
        img: "",
        email: "olivia@example.com",
      },
    ],
    recentActivities: ["Research completed"],
    createdAt: 1679404800,
    updatedAt: 1687363200,
  },
  {
    id: "5",
    name: "Product Enhancement",
    description: "Enhance existing product features based on user feedback.",
    img: "",
    startDate: 1679404800,
    deadline: 1689398400,
    teamMembers: [
      {
        id: "1",
        name: "John Doe",
        img: "",
        email: "john@example.com",
      },
      {
        id: "2",
        name: "Alice Smith",
        img: "",
        email: "alice@example.com",
      },
      {
        id: "3",
        name: "Bob Johnson",
        img: "",
        email: "bob@example.com",
      },
      {
        id: "4",
        name: "Emily Brown",
        img: "",
        email: "emily@example.com",
      },
      {
        id: "5",
        name: "Michael Wilson",
        img: "",
        email: "michael@example.com",
      },
      {
        id: "6",
        name: "Sophia Lee",
        img: "",
        email: "sophia@example.com",
      },
      {
        id: "7",
        name: "David Martinez",
        img: "",
        email: "david@example.com",
      },
      {
        id: "8",
        name: "Emma Taylor",
        img: "",
        email: "emma@example.com",
      },
      {
        id: "9",
        name: "James Rodriguez",
        img: "",
        email: "james@example.com",
      },
      {
        id: "10",
        name: "Olivia Nguyen",
        img: "",
        email: "olivia@example.com",
      },
    ],
    recentActivities: ["User feedback gathered"],
    createdAt: 1679404800,
    updatedAt: 1689561600,
  },
];
